### ISSUE TITLE
Coin disambiguous name for 'datacenter'

### ISSUE THREAD

**Issue by rems** [cyberdyne-corp/genisys#1]
The term 'datacenter' is currently used to represent either:
- a docker container
- a EC2 instance on AWS
- a VM in a VMWare cluster

But all those items can be found on datacenters (in the traditional meaning).

Suggested alternatives:
1. host
2. compute unit
3. compute resource

**Comment by deviantony** [comment]
In fact a datacenter currently represents either:
- a virtualization service (such as a Docker engine on a host, either bare-metal or virtualized - or a virtual VMWare datacenter either on-premise or hosted)
- a cloud service (such as AWS or Google Compute Engine)

For each, a connector is installed to manage the resources (containers, virtual machines), acting as a bridge between genisys and the provider. 

Foreman refers to theses services as 'compute resources', see: http://theforeman.org/manuals/1.8/index.html#5.2ComputeResources

**Comment by deviantony** [comment]
Compute resource should replace the datacenter term.
